### ISSUE TITLE
[FEATURE] Implement navigation bar

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/doticons-website#3]
**Description:**
The navigation bar should have the following specifications:

- It should have a transparent burred background with a white bottom border.
- Logo to the left side, github stars button to the right side. Next to the logo it should be the latest version of the [package](https://www.npmjs.com/package/doticons).
- The navigation bar should be sticky and responsive.

**Attachments:**
![image](https://github.com/eduardconstantin/doticons-website/assets/9199763/8bf6afce-7650-4303-b9ae-766f137553fb)

[Figma file](https://www.figma.com/file/da9o7GcSKEz8wOxXfnBnTy/doticons-website?type=design&node-id=0%3A1&mode=design&t=WGU4s2icu4Dw8tN7-1)

**Comment by sagarxjadhav** [comment]
I'm good at FrontEnd web development please can i do this?

**Comment by myselfprincee** [comment]
> I'm good at FrontEnd web development please can i do this?

Hey, are you Working on this ?? If not, I would love to work on this, and I will deliver quick :)

**Comment by myselfprincee** [comment]
> @sagarxjadhav any progress?

Give him some more time, else you can assign it to me.

**Comment by myselfprincee** [comment]
I just saw He uses Github very less. Only 23 Contributions this year.

**Comment by eduardconstantin** [comment]
I guess it's yours @myselfprincee

**Comment by myselfprincee** [comment]
> I guess it's yours @myselfprincee

Thank you... <3

**Comment by myselfprincee** [comment]
@eduardconstantin The work has been done. Here is the Screenshot 👇
<img width="958" alt="image" src="https://github.com/eduardconstantin/doticons-website/assets/114233864/ee74860c-fe12-4510-a531-a08b407311e9">

Here is how I am handling the version of package :

I installed doticons package abd imported { version } from 'doticons/package.json'; 
Please let me know if I can do it even more efficiently :). Waiting for any suggestions.

**Comment by myselfprincee** [comment]
Please review the code :)

**Comment by myselfprincee** [comment]
#10

**Comment by eduardconstantin** [comment]
I will take a look later today

**Comment by myselfprincee** [comment]
> I will take a look later today

OK 👍
