### ISSUE TITLE
[FEATURE] Implement footer

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/doticons-website#4]
**Description:**
The footer should have the following specifications:

- It should have a transparent burred background with a white top border.
- Contains the text "Built using NextJS" in the middle of the component.
- It should stay at the bottom of the page.

**Attachments:**
![image](https://github.com/eduardconstantin/doticons-website/assets/9199763/29bbfe4b-593e-44b9-a385-feddd4fcbaac)

[Figma file](https://www.figma.com/file/da9o7GcSKEz8wOxXfnBnTy/doticons-website?type=design&node-id=0%3A1&mode=design&t=WGU4s2icu4Dw8tN7-1)

**Comment by Ferdinand-Ogama** [comment]
Hello, kindly assign me this issue.

**Comment by sagarxjadhav** [comment]
sir i'm good at FrontEnd web development i can do this can you please assign this to me?

**Comment by eduardconstantin** [comment]
@sagarxjadhav this one is already assigned

**Comment by Ferdinand-Ogama** [comment]
@eduardconstantin, I'm new to Web and Nextjs. This is one of my first contributions to open-source. 
I'm having a challenge. This is what I see when I start the development server. 
How can I resolve it? 
![Untitled](https://github.com/eduardconstantin/doticons-website/assets/111184823/8a20ec0e-8ccc-4499-965a-70e378b3ffc7)

**Comment by eduardconstantin** [comment]
That is the default template for nextjs.
You have to add your code in layout.tsx

**Comment by Ferdinand-Ogama** [comment]
Noted.

**Comment by Ferdinand-Ogama** [comment]
It's working. Almost through 👍
