### ISSUE TITLE
[FEATURE] Implement dot background

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/doticons-website#5]
**Description:**
The background should have the following specifications:

- It should be made using svg.
- The color of the dots should be white with low opacity (0.4). The background should have an animation, randomly the dots should have the opacity increased to 1 and decreased to the original value.
- It should be responsive.

**Attachments:**
![image](https://github.com/eduardconstantin/doticons-website/assets/9199763/2872aa68-bc5d-47b4-bb7e-e71496b77026)

[Figma file](https://www.figma.com/file/da9o7GcSKEz8wOxXfnBnTy/doticons-website?type=design&node-id=0%3A1&mode=design&t=WGU4s2icu4Dw8tN7-1)

**Comment by myselfprincee** [comment]
Hello @eduardconstantin  I would also love to work on this 🙃. I think i can do this.

**Comment by eduardconstantin** [comment]
@Manasvi1606 how is the progress?

**Comment by myselfprincee** [comment]
Let's see if @Manasvi1606 is working on this..

**Comment by eduardconstantin** [comment]
> <img alt="image" width="958" src="https://user-images.githubusercontent.com/114233864/277409721-6ddcd386-b825-4de7-bb26-4e0a5001e8ec.png">
> Making it responsive would be a challenge

I'm now thinking that the website won't be used too much on mobile but it should look good on bigger screens

**Comment by eduardconstantin** [comment]
ok, we will wait

**Comment by Manasvi1606** [comment]
Great, thanksss

**Comment by Manasvi1606** [comment]
Hi, I have created a pull request please review. I am quite new to next.js so please let me know if there are any improvements. I tried my best to implement what you asked for. Since you said it should look good on big screen so I skipped the responsive part.
Thanks!

**Comment by eduardconstantin** [comment]
@Manasvi1606 looks good, just a few things that need to change
@myselfprincee after I merge his changes can you take over and implement the responsiveness and the animation?

**Comment by myselfprincee** [comment]
Ok 🙂

**Comment by eduardconstantin** [comment]
@myselfprincee the PR is merged

**Comment by myselfprincee** [comment]
> @myselfprincee the PR is merged

Then, what should I have to do ?? 🥲

**Comment by myselfprincee** [comment]
#14
