### ISSUE TITLE
[FEATURE] Implement icons list

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/doticons-website#7]
**Description:**
The icons list section should have the following specifications:
  - The icon containers should be spaced one dot away from each other.
  - The icons are coming directly from the package.

**Attachments:**
![image](https://github.com/eduardconstantin/doticons-website/assets/9199763/0bb39552-a4ee-4269-93d7-d3a541eb1d83)

[Figma file](https://www.figma.com/file/da9o7GcSKEz8wOxXfnBnTy/doticons-website?type=design&node-id=0%3A1&mode=design&t=WGU4s2icu4Dw8tN7-1)

**Comment by 22Yash** [comment]
@eduardconstantin can I work on these

**Comment by eduardconstantin** [comment]
Sure, but I think you should wait for the background to be done first, since the spacing relies on it.

**Comment by 22Yash** [comment]
Okk Can you briefly explain what should do in these . I read that we have to make 2 rows but for what ?

**Comment by eduardconstantin** [comment]
The picture I attached is not visible?

**Comment by jovyllebermudez** [comment]
Hey what to do.
